<Project Sdk="Uno.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net8.0-windows10.0.26100;net8.0-browserwasm;net8.0-desktop</TargetFrameworks>
		<UnoSingleProject>true</UnoSingleProject>
		<OutputType>Library</OutputType>
		<!-- Ensures the .xr.xml files are generated in a proper layout folder -->
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
	</ItemGroup>
	
</Project>
