<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Unai.OpenPivot/Unai.OpenPivot.csproj" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Spectre.Console.Cli" />
	</ItemGroup>

</Project>
