name: OpenPivot Build and Deploy
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      config: 'Release'
      framework: 'net8.0-browserwasm'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 200
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: ./src/Unai.OpenPivot.Gui.Uno/packages.lock.json
    - name: Cache NuGet Packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-packages-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          nuget-packages-
    - name: Restore Dependencies
      run: dotnet restore ./src/Unai.OpenPivot.Gui.Uno/Unai.OpenPivot.Gui.Uno.csproj --locked-mode --force-evaluate
    - name: Build 
      run: dotnet build ./src/Unai.OpenPivot.Gui.Uno/Unai.OpenPivot.Gui.Uno.csproj --no-restore -f $framework -c $config "-p:WasmShellWebAppBasePath=/openpivot/"
    - name: Publish GitHub Pages Artifacts
      uses: actions/upload-pages-artifact@v3
      # if: github.event_name == 'workflow_dispatch'
      with:
        path: ./src/Unai.OpenPivot.Gui.Uno/bin/${{env.config}}/${{env.framework}}/dist/
  deploy:
    needs: build 
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Deploy
    # if: github.event_name == 'workflow_dispatch'
    steps:  
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
